[package]
name = "spicy_api"
authors.workspace = true
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
dotenvy = "0.15.7"
listenfd = "1.0.1"
config = { version = "0.13.3", features = ["yaml"] }
# Path deps
entity = { path = "persistence/entity" }
service = { path = "persistence/service" }
# migration = { path = "persistence/migration" }

[workspace]
members = ["persistence/*"]

[workspace.package]
authors = ["MrFixThis <mrfixthis55@gmail.com>"]

[workspace.dependencies]
anyhow = "1.0.71"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
